// front/vue/src/PageSize.vue
<script setup lang="ts">
import { PAGE_SIZE } from "./settings.json";

interface PageSizeProps {
  currentSize: number
}

type PageSizeEmits = {
  changePageSize: [size: number]
}

defineProps<PageSizeProps>();
defineEmits<PageSizeEmits>();
</script>

<template>
  <div class="page-size">
    <span>Size:</span>
    <button
      v-for="size in PAGE_SIZE.available"
      :key="size"
      :disabled="size === currentSize"
      @click="$emit('changePageSize', size)"
    >
      {{ size }}
    </button>
  </div>
</template>

// front/react/src/PageSize.tsx
import { PAGE_SIZE } from "./settings.json";

interface PageSizeProps {
  size: number;
  onSetSize: (size: number) => void;
}

export const PageSize = ({ size, onSetSize }: PageSizeProps) => {
  return (
    <div className="page-size">
      <span>Size:</span>
      {PAGE_SIZE.available.map((pageSize) => (
        <button
          key={pageSize}
          disabled={size === pageSize}
          onClick={() => onSetSize(pageSize)}
        >
          {pageSize}
        </button>
      ))}
    </div>
  );
};
