// front/react/src/components/dashboard.tsx
import { useState } from "react";

import { CustomerCard } from "./customer/card.tsx";
import { PageSize } from "./controls/page-size.tsx";
import { Pagination } from "./controls/pagination.tsx";

import { parseCustomersList as parseResponse } from "../utils/customer-utils.ts";
import { useAPICall } from "../hooks/use-api-call.ts";

import { PAGE_SIZE } from "../settings.json";

export const Dashboard = () => {
  const [pageSize, setPageSize] = useState(PAGE_SIZE.default);
  const [pageNumber, setPageNumber] = useState(0);
  const { data, loading, error } = useAPICall({
    path: `clients?limit=${pageSize}&offset=${pageSize * pageNumber}`,
    parseResponse,
  });

  if (loading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  if (!Array.isArray(data)) {
    return <div>Sorry, there is nothing here</div>;
  }

  return (
    <div>
      <PageSize size={pageSize} onSetSize={setPageSize} />
      <div className="customer-list">
        {data.map((customer) => (
          <CustomerCard key={customer.id} id={customer.id} />
        ))}
      </div>
      <Pagination pageNumber={pageNumber} onSetPage={setPageNumber} />
    </div>
  );
};

// front/vue/src/Dashboard.vue
<script setup lang="ts">
import { ref } from "vue"
import PageSize from "./PageSize.vue"
import Pagination from "./Pagination.vue"
import CustomerCard from "./CustomerCard.vue"
import useAPICall from "./use-api-call.ts"

import { PAGE_SIZE } from "./settings.json"
import { parseCustomersList } from "./customer-utils.ts"

const pageSize = ref<number>(PAGE_SIZE.default)
const setPageSize = (size: number) => (pageSize.value = size)

const pageNumber = ref<number>(0);
const setPageNumber = (pageNum: number) => {
  pageNumber.value = pageNum
}

const { loading, error, data } = useAPICall({
  path: `clients?limit=${pageSize.value}&offset=${pageNumber.value * pageSize.value}`,
  parseResponse: parseCustomersList,
})
</script>

<template>
  <div v-if="loading">
    Loading...
  </div>
  <div v-else-if="data">
    <PageSize
      :current-size="pageSize"
      @change-page-size="setPageSize"
    />
    <div class="customer-list">
      <CustomerCard
        v-for="{ id } in data"
        :id="id"
        :key="id"
      />
    </div>
    <Pagination
      :current-page-number="pageNumber"
      @change-page-number="setPageNumber"
    />
  </div>
  <div v-else>
    {{ error?.message || 'Oops, an error happened.' }}
  </div>
</template>
