// front/react/src/Pagination.tsx
interface PaginationProps {
    pageNumber: number
    onSetPage: (page: number) => void
}

export const Pagination = ({ pageNumber, onSetPage }: PaginationProps) => {
    return (
        <div className="pagination">
            <button onClick={() => onSetPage(pageNumber - 1)}>&lt; Previous</button>
            <button onClick={() => onSetPage(pageNumber + 1)}>Next &gt;</button>
        </div>
    );
};

// front/vue/src/Pagination.vue
<script setup lang="ts">
interface PaginationProps {
  currentPageNumber: number
}

type PaginationEmits = {
  changePageNumber: [page: number]
}

defineProps<PaginationProps>();
defineEmits<PaginationEmits>();
</script>

<template>
  <div class="pagination">
    <button @click="$emit('changePageNumber', currentPageNumber - 1)">
      &lt; Previous
    </button>
    <button @click="$emit('changePageNumber', currentPageNumber + 1)">
      Next &gt;
    </button>
  </div>
</template>
